### ISSUE TITLE
Allow users to select what columns from the silo to export out.

### ISSUE THREAD

**Issue by glind** [toladata/TolaTables#1]
<a href="https://github.com/mahmoodkhan"><img src="https://avatars.githubusercontent.com/u/717661?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahmoodkhan](https://github.com/mahmoodkhan)**
_Wednesday Apr 15, 2015 at 18:45 GMT_
_Originally opened as https://github.com/mercycorps/tola/issues/6_

---

A user should be able to choose a subset of column from a particular Silo to be exported. This functionality should be implemented in a way that is reusable for the various  export end points.

**Comment by joy-humanitec** [comment]
Seems to work for exporting as csv.
