### ISSUE TITLE
Direct users not logged in, to the Google Auth, not the local page

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#194]
If a user is not logged in and they have a link to a silo,  they are directed to 

![uploads/8b33ecb4-50ce-4653-a101-0f4baf26928f/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8b33ecb4-50ce-4653-a101-0f4baf26928f%2Fblob)

Instead,  I think we want them directed to the Google Login: 

![uploads/4a45352c-520f-4b7f-933f-7c8b68ae3427/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4a45352c-520f-4b7f-933f-7c8b68ae3427%2Fblob)

**Comment by glind** [comment]
n/a
