### ISSUE TITLE
Editing a row in a silo does not allow user to edit column that it doens't contain data for

### ISSUE THREAD

**Issue by gartea** [toladata/TolaTables#253]

**Comment by glind** [comment]
This is a very confusing bug report.  Can we get some more clarification in the details?

**Comment by karrla** [comment]
If Column A has no data in it's rows, and the user tries to ***add*** data to Column A by editing one of tables' rows, the edit does not save. 

But if the user only tries to ***edit*** the data in the columns that do have data, the edits save. 

Example: I tried to enter zeros across full row in the table and nothing happened. Then I tried to enter zeros in just the columns:
formhub/uuid
meta/instanceID
user_assigned_id

and the edit saved. 

![image](https://user-images.githubusercontent.com/15875770/32692938-2632ed38-c6d6-11e7-84f9-4cab1a0a9773.png)
