### ISSUE TITLE
Error: Importing Google Spreadsheet gives a 404 error

### ISSUE THREAD

**Issue by joy-humanitec** [toladata/TolaTables#284]
Support ID: <a href="https://toladata.freshdesk.com/helpdesk/tickets/44">44</a>

On demo server

Unable to import a Google Spreadsheet. User gets a 404 error.

Importing for CSV and ONA work fine.

![image](https://user-images.githubusercontent.com/29476180/32721561-29c279b8-c867-11e7-8eb5-7e92ff5db680.png)

**Comment by glind** [comment]
GOOGLE_API_CLIENT_ID and GOOGLE_API_KEY environment variables are not configured in Marathon or Deployment.

**Comment by Menda** [comment]
Different errors found.

**Staging:**

![image.png](https://images.zenhubusercontent.com/5a156c3d8a75884b90886fba/e8a954f7-ed74-40e2-b86b-f1a5db7635b4)

**Demo:**

GET https://demo-track.toladata.io/get_sheets_from_google_spredsheet/?spreadsheet_id=1_ORuoFq_PYqd1Kb5csDYbaTvkYUBiSD5pzNBt2ItxD8 404 (Not Found) JQuery

**Live:**

Failed to load resource: the server responded with a status of 404 (Not Found)
https://track.toladata.io/get_sheets_from_google_spredsheet/?spreadsheet_id=1TNBELjJQ_faHh1w6WKhzcGc9MEv9TIuWTvyps9THjvE
