### ISSUE TITLE
Edit Columns Errors: Cannot add/delete or edit a Table's columns

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#286]
ServerSelectionTimeoutError at /edit_columns/60/
localhost:27017: [Errno 111] Connection refused
Request Method:	POST
Request URL:	http://demo.tolatables.app.tola.io/edit_columns/60/
Django Version:	1.11.3
Exception Type:	ServerSelectionTimeoutError
Exception Value:	
localhost:27017: [Errno 111] Connection refused
Exception Location:	/usr/local/lib/python2.7/site-packages/pymongo/topology.py in select_servers, line 186
Python Executable:	/usr/local/bin/python
Python Version:	2.7.14

**Comment by sanjuroj** [comment]
@karrla There is currently a problem with editing column headers (the edits are saved to the Mongo DB but not to the MySql/Postgres DB).  But this line makes it look more like a problem connecting to the MongoDB than a problem of the modifying columns:
`localhost:27017: [Errno 111] Connection refused`

I'm working on the saving to the non-MongoDB problem, should I use this issue or open a new one?
