### ISSUE TITLE
Cannot set table to Auto-Update - fails to finish loading. No error

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#294]
### Current Behavior

Set Auto-Pull on a few tables and the command never finishes loading

![uploads/bbee859a-b500-4420-bd2c-77276ce74841/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbbee859a-b500-4420-bd2c-77276ce74841%2Fimage.png)

### Expected Behavior

User clicks auto-pull daily or weekly and the setting is set. Then the table updates with any new data the following day or week, which ever was set.

**Comment by abarquero** [comment]
Please, add estimation for this issue.

**Comment by jefmoura** [comment]
@abarquero this ticket is done but not closed.
