### ISSUE TITLE
GSheet import is aborted for first time users

### ISSUE THREAD

**Issue by sanjuroj** [toladata/TolaTables#313]
When a google sheet is imported for the first time by a new user, Google asks for permission to grant TolaData access to your account and then doesn't proceed to the import.  Instead, it dumps users back onto previous page they were viewing.  The second time the import is attempted it works fine.

This can be tested by deleting the socialauth_usersocialauth entry for a user, which will cause socialauth to create a new user (with the same email address).

**Comment by Menda** [comment]
@joy-humanitec In our case it was not even possible to open the file picker because of several issues, which I fixed today. Can you check in dev and staging if you are able to reproduce this ticket's error?

**Comment by joy-humanitec** [comment]
@Menda 

Staging: I seem to have a different error

ACTION: Deleted social auth > logged in again(new auth created) > clicked on Track > clicked on Import Google Spreadsheet > Was asked to allow access to Google Drive > selected my spreadsheet

RESULT: Error 404: Not Found (I created a new document in the drive for selection)
