### ISSUE TITLE
Ona Import: Same Table, different results

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#412]
### Current behavior
I Imported the same Ona table 10 times in a row and the system created different tables with various row count (blank rows) 

![import 2](https://user-images.githubusercontent.com/15875770/36205884-b3c00a82-1190-11e8-8ab0-a1e039cc5769.gif)

### Expected behavior
When I import the same Ona table I expect to get the same results, unless additional data has been submitted to the form between the imports

### Steps to reproduce the behavior

1. import the same table multiple times
2. check the row count each time

**Comment by yilmazbekdemir** [comment]
I checked this ticked but I couldn't reproduce this behaviour

**Comment by jefmoura** [comment]
@karrla could you check it again, pls?
