### ISSUE TITLE
Saving a column with a new name deletes its content

### ISSUE THREAD

**Issue by leonholub** [toladata/TolaTables#417]
### Current behavior
When editing a column name  (url  /edit_columns/##) i saves the new column name but the content of the column is lost.

### Expected behavior
A rename does not delete all the data in the column.

### Steps to reproduce the behavior

1. Go to any silo detail page /silo_detail/##/
2. From the tabs select Edit -> Edit or Delete Columns you will get redirected to view edit_columns/##/
3. Edit any of the column names and save the form
4. Navigate back to the table (if you are not getting redirected yet) and look at the columns you edited

**Comment by jefmoura** [comment]
- This is the current behavior, right?
- What is the expected behavior?
- Could you define the steps to reproduce the behavior?

**Comment by leonholub** [comment]
Yes, this is the current behaviour. The expected behaviour would be that a rename does not delete all the data in the column.

###Steps to reproduce:
1. Go to any silo detail page /silo_detail/##/
2. From the tabs select Edit -> Edit or Delete Columns you will get redirected to view edit_columns/##/
3. Edit any of the column names and  save the form
4. navigate back to the table (if you are not getting redirected yet) and look at the columns you edited

**Comment by jefmoura** [comment]
It seems to be working. Maybe, it was fixed with another issue.

**Comment by leonholub** [comment]
Okay, we should keep an eye on this. Something like that should be covered by a test case anyway.
