### ISSUE TITLE
Staging: The Track tables that the Custom Forms create are loading errors

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#430]
### Current behavior
![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/f4f1b0dd-21e6-4413-b6de-c01519b2640c)

### Expected behavior
Track Table created on publish and is accessible by the user

### Steps to reproduce the behavior

1. Create Form
2. Publish Form to WFL1
3. Open the Track and find the Table that was created
4. Open the Table
5. See Error
6. Go back to Activity Add Data to Form (/activity/forms/##/view)
7. Click on the "Data is saved here"
8. See Error

### Authentication method

[] Google
[] Microsoft
[X] Username / password
[] Is it a new user?

### Permissions

[X] OrgAdmin
[] ProgramAdmin
[] ProgramTeam
[] ViewOnly
[] Other / I don't know

**Comment by leonholub** [comment]
I've looked into the issue and it seems to be caused by migrations not applying correctly. I will fix the migrations.

**Comment by leonholub** [comment]
I was able to fix the migration issue, but now there is some problem with the background tasks. Silos get stuck on this message. I will try to fix it now![screenshot-dev-track.toladata.io-2018.03.07-12-17-08.png](https://images.zenhubusercontent.com/5a1c0d338a75884b9088e535/180d819f-69c3-4800-8dea-0637c0e2ced3)

**Comment by leonholub** [comment]
It's working now
