### ISSUE TITLE
Track share Table by WFL1

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#465]
### Story
Users want to be able to share their Tables with their team members who are in their WFL1/Organization, not just individuals. We need to provide a way to share with their WFL1, without having to share publicly.

### Acceptance Criteira
GIVEN a user has a Track Table
WHEN they choose to share their Table
THEN they are given the option to pick one or more of their WFL1 to share their Table with. 

### Additional Details
Currently when a user creates a Table (Silo) the table is not associated with their Organization, only if the user published a Form in Activity, which creates a new Table, does the Table get associated with an Organization

**Comment by karrla** [comment]
@yilmazbekdemir 
I see the section to share with the WFL1, but I the section is not active.
I can't choose a wFL1 nor can I type one in the field. 

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/afd05dae-ad15-4ed3-b3c7-b535ae9d5443)

**Comment by yilmazbekdemir** [comment]
@karrla Is your user has workflowlevel1? That selectbox contains users workflows.

**Comment by karrla** [comment]
@yilmazbekdemir 
ha! yes, the user has a lot of WFL1 :)  

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/05bc017d-f970-42e8-b4c8-2084d22eca2e)

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/9272490b-c871-43c9-8879-cc3d4fa11650)
