### ISSUE TITLE
Merge: Link to new Table - After Merging tables the user should see a link to the new Table

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#478]
### Current behavior
When a user merges two tables in Track (in production) after going through all the steps and they click submit the user stays on the same page and does not see a link to the new table without going back to the homepage

### Expected behavior

When a user merges two tables in Track (in production) after going through all the steps and they click submit they see a link to their new merged table.

### Steps to reproduce the behavior

1. Merge two tables
2. After submit 
3. Notice there is no link to the new merged Table

**Comment by yilmazbekdemir** [comment]
@karrla I tested this issue on Dev. After click submit, system redirecting user to silo detail page of merged table. I think it's (opening detail of new table) better than showing link on the merge page.
