### ISSUE TITLE
Add the user who submitted data to  all published Activity Form Tables

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#482]
### Story
Similiar to #477
When a user creates a form in Activity and publishes it, they would like the table created in Track to capture who submitted the data in each entry 

### Acceptance Criteria

GIVEN a user has a published form in Activity

WHEN they enter data into the form

THEN each submission will have the username of who submitted the data in the Track table.

**Comment by jefmoura** [comment]
@karrla and @joy-humanitec 
Is it not better to add the user's `name` instead of the `username`? I think it's more readable when we have `Jeferson Moura` than `jefmoura`.

**Comment by karrla** [comment]
@jefmoura yes "Name" or "email" would be better than username. Please note in the future users will be able to enter submissions to the form without having to log in, so we will not always know a name, username nor their email so the field should not be required.
