### ISSUE TITLE
Prevent users to share their tables with themselves

### ISSUE THREAD

**Issue by yilmazbekdemir** [toladata/TolaTables#486]
### Current behavior

Users can share their tables with themselves. They can share by writing their user names to share box or they can share by sharing with their organizations.
 
### Expected behavior
Users can't share their tables with themselves. If they share table with organization level then they still can't see their tables on the 'Data Tables Shared with you' section.

### Steps to reproduce the behavior

1. GIVEN user has a table they want to share
2. WHEN they search individual members at the shared box on the Silo edit page
3. THEN they can see and select their names

1. GIVEN user has a table they want to share
2. WHEN they check the 'share with organization button' and click the save
3. THEN they see that table on their 'Data Tables Shared with you' section on the silo list page.

![Screen Shot 2018-05-04 at 15.37.28.png](https://images.zenhubusercontent.com/5acf4ca94b5806bc2bcecabe/e99b350e-d623-4fc3-8d7a-1b4f438b7c6b)

![Screen Shot 2018-05-04 at 15.37.59.png](https://images.zenhubusercontent.com/5acf4ca94b5806bc2bcecabe/3c1392a0-e84c-4cf8-b26b-4b91b4481ae4)
### Additional details
Environment: [**dev**/**staging**/**demo**/**production**]

**Comment by karrla** [comment]
@yilmazbekdemir                  
Yes you are right, this ticket looks good, but is there a plan to make another section that says "Data Tables shared with your Org"?

So - 
WHEN a user shares a Table with their Org
THEN they will see their table under the "Data Tables shared with your Org" section and under "Data Tables you Own" section
