### ISSUE TITLE
Add permission control to silo edit page

### ISSUE THREAD

**Issue by yilmazbekdemir** [toladata/TolaTables#487]
### Current behavior
If user try to access silo edit page with url then they can access the page even they don't have a permission on that table.

### Expected behavior
If users try to access silo edit page and if they are not owner or table isn't shared with them, then they can't access the page.

### Steps to reproduce the behavior

1. GIVEN user try to access silo edit page with url (/silo_edit/{id}) 
2. WHEN they haven't any permission with that table
3. THEN they can still access to page.

![Screen Shot 2018-05-04 at 15.48.30.png](https://images.zenhubusercontent.com/5acf4ca94b5806bc2bcecabe/abdff89c-f95a-48ce-a8c5-36be5c385448)

![Screen Shot 2018-05-04 at 15.49.09.png](https://images.zenhubusercontent.com/5acf4ca94b5806bc2bcecabe/6ad0a207-7e8e-4d72-b1af-33c6ed343ce7)

**Comment by karrla** [comment]
I would suggest that 

Expected behavior
If users try to access silo edit page and if they are not owner or table isn't shared with them, then they CANNOT EDIT the silo edit page.

**Comment by karrla** [comment]
Oh, ok if they just guess the URL or someone sends them a link? You are right they should not be able to edit the silo page.
