### ISSUE TITLE
 Sharing: the user list for sharing is not filtered by Org - causes view/error issue.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#508]
### Current behavior
Issue: the user list for sharing is not filtered by Org and is causing issues with sharing Tables (with) data across Orgs 

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/4669f839-cef5-4aa7-b865-0f4e9204c0d5)670217190

### Expeceted Behavior
The user list for sharing is  filtered by Org, so users cannot share across Orgs

### Steps to reproduce the behavior

1.  Import a Google Sheet 
https://docs.google.com/spreadsheets/d/1pDaQ1hqlKA9pyyFS5UwihgUusuVabwMi3AzYkLzXdIs/edit?usp=sharing
2. View the Table (/silo_detail/###/)
3. Share the Table with a user who is not in your Org . (/silo_edit/###/)

### Additional details
Environment: **dev**/**staging**

**Comment by jefmoura** [comment]
@karrla can you check it? It's working for me.

**Comment by karrla** [comment]
@jefmoura 
I am no longer getting the error in staging. So this can be moved to done
