### ISSUE TITLE
Auto-push of Data table to GoogleSheet

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#70]
Auto-push of the Data tables to GoogleSheet.
This will help to update external dashboards (using sheets and fusion tables) automatically. # - 
Auto-push of the Data tables to GoogleSheet.
This will help to update external dashboards (using sheets and fusion tables) automatically.

**Comment by karrla** [comment]
Duplicate: https://github.com/toladata/TolaTables/issues/63

**Comment by mahmoodkhan** [comment]
This is a duplicate of https://github.com/toladata/TolaTables/issues/63
