### ISSUE TITLE
Import from ONA - How does using repeats affect merge/export functions in Tola Tables

### ISSUE THREAD

**Issue by glind** [toladata/TolaTables#9]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Tuesday Nov 03, 2015 at 08:59 GMT_
_Originally opened as https://github.com/mercycorps/tola/issues/68_

---

atpham@mercycorps.org We were able to import two tables from Ona that have repeats (repeats creates two sheets in the workbook) and merge the two tables. We could view, edit the first sheet. When tried to "SHARE" and create new Google Sheet, it created the google sheet but with no data. Wondering if this has something to do with the repeats why it didn't export?

**Comment by mahmoodkhan** [comment]
I used a XLSForm that has repeats and uploaded it to my ONA account, then I entered a couple records each with repeating household member names and age. I then pulled that data down to tolatables. I was able to see all of the repeats data in a single column and were also able to export it to Google Spreadsheet.

If this is still an issue, please send me the XLSForm you're using and the step by step instructions on how to replicate this issue.

**Comment by karrla** [comment]
Documenting the details on a repeats in XLSform to Ona: 

See Ona table how each Beneficiary is viewable in the Beneficiary repeats column:
 "Repeated data with 3 answers." 
 https://ona.io/tola/14815/126766#/table

Imported Tola Tables with repeats: 
https://tola-tables-demo.mercycorps.org/silo_detail/96/

XLSform with repeats attached. 
[CashTransferSurvey_Tolastan_repeats.xlsx](https://github.com/toladata/TolaTables/files/294413/CashTransferSurvey_Tolastan_repeats.xlsx)

**Comment by karrla** [comment]
also see TW http://tola.work/helpdesk/tickets/471/
